### ISSUE TITLE
automatically check the function input

### ISSUE THREAD

**Issue by gxli** [mattja/sdeint#12]
Hi, 

thanks for the cool package. However, there seems to be a small issue with the return value of the input function

if I return lists in function f and function G, the integrator seems to be confused and then allocate a huge amount of memory. After manually converting my return values into numpy.array, the problem is solved. It took me an hour to figure this out.
 
Therefore, it would be easier if the integrator automatically checks the return values of the input function, to avoid confusing the reader. 

Thanks!

**Comment by mattja** [comment]
Thanks for raising this.
At the very least itoint() and stratint() should have proper docstrings that explain the requirements for f and G. I'll fix them.

I can't quite replicate the behavior you describe though. 
If I return lists in function f and G, it fails cleanly throwing `AttributeError: 'list' object has no attribute 'ndim'`
Could you please show me the input you used to make it fail badly?

**Comment by gxli** [comment]
Hi Mattew,

many thanks for the reply. Unfortunately I could not find the old version of the code, and indeed now it throws  "AttributeError: 'list' object has no attribute ‘ndim’”.

thanks for the nice work and please remove the issue since I can not reproduce it. 

Cheers, G



> many
