### ISSUE TITLE
Random seed for reproducibility 

### ISSUE THREAD

**Issue by PHTHK** [mattja/sdeint#14]
It is possible to have random seed input as an argument 
(e.g. `itoEuler(f, G, y0, tspan, random_state=1)`) for reproducibility purpose?

Thanks

**Comment by mattja** [comment]
It is not necessary to add that functionality to sdeint.

sdeint uses numpy to generate random numbers. 

If you want to use a known random seed, just call 
`numpy.random.seed(1234)`
at the start of your code.  This takes an integer seed between 0 and 2**32-1 inclusive.

N.B. If you are running multiple python processes or threads to get many realizations of a random process, such as on a cluster, then you need to make sure that each python process uses a different seed.

**Comment by superconvergence** [comment]
Formally, different seeds will ensure independence of the random generator instances but not necessarily independent random number sequences. If this is important for your setup, you can use an external random generator that supports a method to produce independent streams (see e.g. [github/randomgen](https://github.com/bashtage/randomgen)). Note that sdeint integrators already allow easy input of random increments via the `dW` argument.

**Comment by mattja** [comment]
This is a good point. Thanks for pointing out the randomgen project.
