### ISSUE TITLE
Allow passing a numpy Generator for random numbers

### ISSUE THREAD

**Issue by PFMassiani** [mattja/sdeint#21]
Hello,

This is a follow up on #14 given numpy's latest recommendation regarding random number generation, which can be found [here](https://numpy.org/doc/stable/reference/random/index.html#random-quick-start).

In short, using `np.random.XXX` is now legacy, and the recommended usage is:
```python
rng = np.random.default_rng(seed=0)
rng.normal()
```
And instead of setting the global seed, one should pass the `Generator` instance to the place where it is needed.
AFAIK, `sdeint` does not allow passing a `Generator` instance.

It would be nice to incorporate this feature for compatibility with newer code, e.g., with `sdeint` using a global `Generator` instance that could be set by the user.

Thanks

**Comment by mattja** [comment]
Excellent suggestion.  I'll implement this in the next couple of weeks as time permits.
Adding a `generator` keyword argument in all relevant sdeint functions. 

If omitted `generator=None`, it can just default to instantiate its own  `np.random.default_rng()` .
I'll assume no need for bitwise backwards compatibility with the old behavior.
