### ISSUE TITLE
bibtex & integration order

### ISSUE THREAD

**Issue by matibilkis** [mattja/sdeint#25]
Hi guys, i'm citing you, and I believe you need to add a citation format to the .md file
I got this far...
```
  @software{sdeint,
    author = {Matthew Aburn and Yoav Ram},
    url = {https://github.com/mattja/sdeint},
  }
```
thanks a lot for implementing all this!
BTW, we noticed that the algorithm for stochastic Ito integration you have is order 1.0, however Rossler paper is titled "second order RK...", and mathematica has a routine that implements order 3/2 (in dt). Is this correct ? Maybe i'm misleading what second order means here (probabily \sqrt{dt}^2), but are you planning to implement higher order algorithms?
thanks again

**Comment by mattja** [comment]
Thanks for citing this work.  The preferred citation is the PhD thesis where `sdeint` was originally published:
```BibTeX
@phdthesis{aburn_critical_2017,
	author = {Aburn, Matthew J.},
	title = {Critical fluctuations and coupling of stochastic neural mass models},
	school = {The University of Queensland},
	year = {2017},
	month = jan,
	doi = {10.14264/uql.2017.148},
}
```

Regarding the order of these algorithms, you might be looking at the wrong Rößler paper. 
`sdeint` currently implements the method from Rößler 2010 which is an order 1 _strong_ method.
By contrast, Rößler 2009 introduces an order 2 _weak_ method. 

"order" refers to convergence with respect to the size of  `h`, the discrete time step.
Kloeden and Platen 1999 has a good discussion of _strong_ and _weak_ convergence. 
The Rößler papers above also define these in the Definition 1.1 of each paper.
